name: barbero_dormilon
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: 2.0.2
  cupertino_icons: ^1.0.5
  animated_text_kit: ^4.2.2
  material_design_icons_flutter: ^5.0.6996
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  oktoast: ^3.3.1
  dartz: ^0.10.1
  auto_route: ^5.0.2
  flutter_svg: ^1.1.5
  lottie: ^1.4.3
  flash: ^2.0.5

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter

  freezed: ^2.2.0
  json_serializable: ^6.5.3
  lint: ^1.10.0
  auto_route_generator: ^5.0.3
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/

